parser/parser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parserapp.urls', namespace='parser')),
    path('user/', include('userapp.urls', namespace='user')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

parser/parserapp/urls.py
from django.urls import path
from parserapp import views
app_name = 'parserapp'
urlpatterns = [
    path('', views.BookListView.as_view(), name= 'index'),
    path('work/<int:pk>', views.WorkDetail.as_view(), name= 'work'),
    path('comment/<int:id>', views.CommentCreateView.as_view(), name= 'comment'),
]

parser/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView
from .views import UserCreateView
app_name = 'userapp'
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name= 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name= 'register'),
]

parser/parserapp/models.py
from django.db import models
from userapp.models import UserAuthor
# Create your models here.

class NameStamp(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        abstract = True

class Author(NameStamp):
    def __str__(self):
        return self.name

class Comment(NameStamp, models.Model):
    comment = models.TextField()
    def __str__(self):
        return self.name, self.comment

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author, related_name='books_author')
    content = models.TextField()
    href = models.URLField()
    img_href = models.ImageField(upload_to='books', null=True, blank=True)
    comments = models.ManyToManyField(Comment)
    user = models.ForeignKey(UserAuthor, null= True, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    def is_img(self):
        return bool(self.img_href)
    def get_comments(self):
        return self.comments.all()

    def count_comments(self):
        return self.comments.count()

parser/userapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class UserAuthor(AbstractUser):
    email = models.EmailField(unique=True)
    is_author = models.BooleanField(default=False, verbose_name='Это автор')

parser/parserapp/forms.py
from django import forms

from .models import Comment


# class CommentForm(forms.Form):
#     name = forms.CharField(label='Ваше имя')
#     comment = forms.CharField(label='Коментарий')
class CommentForm(forms.ModelForm):
    comment = forms.CharField(label='',
                              widget=forms.Textarea(attrs={'class': 'form-control',
                                                           'placeholder': 'Ваш комментарий'}))
    class Meta:
        model = Comment
        fields = ['comment']

parser/userapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import UserAuthor
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = UserAuthor
        fields = ['username', 'email', 'password1', 'password2']

parser/parserapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin

from parserapp.forms import CommentForm
from parserapp.models import Book, Comment
from userapp.models import UserAuthor

# Create your views here.
class BookListView(ListView):
    paginate_by = 12
    model = Book
    queryset  = Book.objects.prefetch_related('authors')
    template_name = 'parserapp/index.html'

class WorkDetail(DetailView):
    model = Book
    template_name = 'parserapp/work.html'
    queryset = Book.objects.prefetch_related('authors', 'comments')

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'parserapp/comment.html'
    form_class = CommentForm
    def form_valid(self, form):
        Book.objects.get(id=self.request.path.split('/')[-1]).comments.create(name=self.request.user,
                                             comment=f'{self.request.POST['comment']}')
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(CommentCreateView, self).get_context_data(**kwargs)
        context['book'] =Book.objects.prefetch_related('authors').get(id = self.request.path.split('/')[-1])
        return context
    def get_success_url(self):
        return reverse(viewname='parserapp:work', kwargs={'pk': self.request.path.split('/')[-1]})

parser/userapp/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import UserRegisterForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .models import UserAuthor


# Create your views here.
class UserLoginView(LoginView):
    template_name = 'userapp/login.html'

class UserCreateView(CreateView):
    model = UserAuthor
    template_name = 'userapp/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('parserapp:index')

parser/parserapp/templates/parserapp/book_list.html
{% extends "base.html" %}
{% block titel %}
<title>Shop Homepage - Start Bootstrap Template</title>
{% endblock titel %}
{% block header %}
<header class="bg-dark py-5">-->
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Список популярных книг</h1>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
        <section class="py-5">

            <div class="container px-4 px-lg-0 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-4 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {%for item in object_list%}
                    <a href="{% url 'parser:work' item.id %}">
                    <div class="col mb-5">
                        <div class="card h-100" >
                            <div class="card-body p-0">
                                <div class="text-center">
                                    <img class="card-img-top" src='{{item.img_href.url}}' />
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{item.title}}</h5>
                                    <h5 class="fw-semibold">Автор:</h5>
                                    {%for author in item.authors.all%}
                                    <h5 class="fw-semibold">{{author}}</h5>
                                    {%endfor%}
                                </div>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>
        </section>
{% endblock %}

parser/parserapp/templates/parserapp/comment.html
{% extends "base.html" %}

{% block titel %}
<title>Комментарий к книге {{book.title}}</title>

{% endblock titel %}
{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{book.title}}</h1>
            {%for author in book.authors.all%}
            <p class="lead fw-normal text-white-50 mb-0">{{author}}</p>
            {%endfor%}
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<br>
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <form method="POST" id = 'commentForm'>
            {% csrf_token %}
            {#form.as_p#}
            {% for field in form %}

                <p>{{field.label_tag}}</p>
            <hr>
                {% for error in field.errors %}
                    <p style="color: red">{{error}}</p>
                {% endfor %}
            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary" id="commentButton">Отправить комментарий</button>
        </form>
    </div>
</section>

{% endblock %}

parser/parserapp/templates/parserapp/index.html
{% extends "base.html" %}

{% block titel %}
<title>Список популярных книг</title>

{% endblock titel %}
{% block header %}
<header class="bg-dark py-2">-->
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Список популярных книг</h1>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-0 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-6 row-cols-md-6 row-cols-xl-6 justify-content-center">
                {%for item in object_list%}
                <a class='nav-link' href="{% url 'parser:work' item.id %}">
                <div class="col mb-5">
                    <div class="card h-100" >
                        <div class="card-body p-0">
                            <div class="text-center">
                                <img class="card-img-top" src='{{item.img_href.url}}' />
                                <!-- Product name-->
                                <h4 class="fw-bolder text-black">{{item.title}}</h4>
                                <h4 class="fw-semibold text-black">Автор:</h4>
                                {%for author in item.authors.all%}
                                <h4 class="fw-semibold text-black">{{author}}</h4>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                </div>
                </a>
                {%endfor%}
            </div>
            <hr>
            <div class="pagination justify-content-center">
                {% for object_list in page_obj %}
                    {# Each "contact" is a Contact model object. #}
                {% endfor %}
                <p>
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1" class='nav-link'>
                            <h4 class="fw-semibold"> Первая &nbsp&nbsp&nbsp</h4>
                            </a>
                            <a class='nav-link' href="?page={{ page_obj.previous_page_number }}">
                                <h4 class="fw-semibold">Предыдущая &nbsp&nbsp&nbsp </h4>
                            </a>
                        {% endif %}

                        <span class="current">
                            <h4 class="fw-bolder">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</h4>
                        </span>

                        {% if page_obj.has_next %}
                            <a class='nav-link' href="?page={{ page_obj.next_page_number }}">
                                <h4 class="fw-semibold">&nbsp&nbsp&nbspСледующая &nbsp&nbsp&nbsp</h4></a>

                            <a class='nav-link' href="?page={{ page_obj.paginator.num_pages }}">
                                <h4 class="fw-semibold">Последняя &nbsp&nbsp&nbsp&raquo;</h4></a>
                        {% endif %}
                    </span>
                </p>
            </div>
        </div>
    </section>
{% endblock %}

parser/parserapp/templates/parserapp/work.html
{% extends "base.html" %}

{% block titel %}
<title>{{object.title}}</title>

{% endblock titel %}
{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{object.title}}</h1>

            {%for author in object.authors.all%}
            <p class="lead fw-normal text-white-50 mb-0">{{author}}</p>
            {%endfor%}
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <img src='{{object.img_href.url}}' width="300"/>
                    <div class="text-start">
                        <h5 class="fw-semibold">Аннотация</h5>
                        <h5 class="fw-normal">{{object.content}}</h5>

                    </div>
            </div>
</section>
<div class="container px-4 px-lg-5 mt-5">
<div class="text-start">
<a href="{% url 'parser:comment' object.pk %}">
    <button type="submit" class="btn btn-primary" id="commentButton">Добавить комментарий</button></a>
</div>
</div>
<div class="container px-4 px-lg-5 mt-5">
<div class="text-start">
    <h5 class="fw-bolder">Коментарии:</h5>

<section class="py-5">
    {% if object.comments.all.count > 0 %}
        {%for comment in object.comments.all%}
                            <hr>
                            <h5 class="fw-semibold">Автор комментария: {{comment.name}}</h5>
                            <h5 class="fw-normal">{{comment.comment}}</h5>
        {%endfor%}
    {%endif%}
</div>
</div>
</section>

{% endblock %}

parser/templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        {% block titel %} {% endblock titel %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">
                    <h4>Начальная страница</h4>
                </a>
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'user:logout' %}">
                    {% csrf_token %}
                    <p class="navbar-brand"> {{user.username}}</p>
                    <hr>
                    <button type="submit" class="btn btn-primary">Выйти</button>
                </form>
                {% else %}
                <div>
                    <a class="navbar-brand" href="{% url 'user:login' %}">Вход</a>
                    <hr>
                    <a class="navbar-brand" href="{% url 'userapp:register' %}">Регистрация</a>
                </div>
                {% endif %}
<!--                <a class="navbar-brand" href="/book_list">Список книг</a>-->
<!--                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>-->
<!--                <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">-->
<!--                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>-->
<!--                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>-->
<!--                        <li class="nav-item dropdown">-->
<!--                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>-->
<!--                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                                <li><a class="dropdown-item" href="#!">All Products</a></li>-->
<!--                                <li><hr class="dropdown-divider" /></li>-->
<!--                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>-->
<!--                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>-->
<!--                            </ul>-->
<!--                        </li>-->
<!--                    </ul>-->
                </div>
            </div>
        </nav>
        <!-- Header-->
        {% block header %} {% endblock header %}
        <!-- Сontent-->
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Парсер сайта author.today</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

parser/userapp/templates/userapp/login.html
{% extends "base.html" %}

{% block titel %}
<title>Аутификация пользователя</title>

{% endblock titel %}
{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Вход пользователя</h1>

        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <form method="POST" id = 'commentForm'>
            {% csrf_token %}
            {#form.as_p#}
            {% for field in form %}
                <p>{{field.label_tag}}</p>
            <hr>
                {% for error in field.errors %}
                    <p style="color: red">{{error}}</p>
                {% endfor %}
            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary" id="commentButton">Войти</button>
        </form>
    </div>
</section>
{% endblock %}

parser/userapp/templates/userapp/logout.html
{% extends "base.html" %}

{% block titel %}
<title>Выход пользователя {{user.username}}</title>

{% endblock titel %}
{% block header %}

{% endblock header %}
{% block content %}

{% endblock %}

parser/userapp/templates/userapp/register.html
{% extends "base.html" %}

{% block titel %}
<title>Регистрация пользователя</title>

{% endblock titel %}
{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Вход пользователя</h1>

        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <form method="POST" id = 'commentForm'>
            {% csrf_token %}
            {#form.as_p#}
            {% for field in form %}
                <p>{{field.label_tag}}</p>
            <hr>
                {% for error in field.errors %}
                    <p style="color: red">{{error}}</p>
                {% endfor %}
            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary" id="commentButton">Регистрация</button>
        </form>
    </div>
</section>
{% endblock %}